AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Webpage Video Capture using Container Image support for AWS Lambda

Parameters:
  BucketName:
    Type: String
    Description: Bucket name for video captures
  ImageUri:
    Type: String
    Description: Lambda container image repository URI

Globals:
  Function:
    Environment:
      Variables:
        BUCKET_NAME: !Ref BucketName

Resources:
  CapturePage:
    Type: AWS::Serverless::Function
    Properties:
      Description: Capture a video of a webpage loading and upload to S3
      PackageType: Image
      ImageUri: !Ref ImageUri
      MemorySize: 2048
      Timeout: 60
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              - Fn::Join:
                - ':'
                - - 'arn'
                  - 'aws'
                  - 's3::'
                  - Fn::Join:
                    - '/'
                    - - !Ref BucketName
                      - 'capture'
                      - '*'

  CapturePageLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${CapturePage}
      RetentionInDays: 7
